- app/api/seniors/help/[helpId]/route.ts
- app/api/seniors/help/route.ts
- backend/seniors/helps/SeniorHelpModel.ts
- backend/seniors/helps/applications/dtos/SeniorRequest.ts
- backend/seniors/helps/applications/dtos/SeniorResponse.ts
- backend/seniors/helps/applications/usecases/SeniorHelpUseCases.ts
- backend/seniors/helps/domains/entities/SeniorHelp.ts
- backend/seniors/helps/domains/repositories/SeniorHelpRepositoryInteface.ts
- backend/seniors/helps/infrastructures/SeniorHelpInfrastructure.ts
- backend/seniors/helps/infrastructures/mappers/SeniorHelpMapper.ts
> [Feat] 헬프 시스템 구현 (2) - 시니어 회원 헬프 시스템

- app/api/Next_POLAR_All_APIs.postman_collection.json
> [Docs] API 명세서 Postman Collection JSON 파일 추가.

- backend/chats/messages/applications/dtos/ContactMessageDtos.ts
- backend/chats/messages/applications/usecases/ContactMessageUseCases.ts
- backend/chats/messages/domains/entities/contactMessage.ts
- backend/chats/messages/infrastructures/mappers/ContactMessageMapper.ts
- backend/chats/messages/infrastructures/repositories/SbContactMessageRepository.ts
- lib/getUserName.ts
> [Refactor] contact_messages 컬럼에 nickname 추가.

- app/(pola)/chats/[roomId]/ChatRoom.module.css
- app/(pola)/chats/[roomId]/ChatRoom.tsx
- app/(pola)/chats/[roomId]/page.module.css
- app/(pola)/chats/[roomId]/page.tsx
- app/_components/ProfileCard.module.css
- app/api/chats/rooms/[chatRoomId]/messages/route.ts
- app/api/users/route.ts
- backend/chats/messages/applications/dtos/ContactMessageDtos.ts
- backend/chats/messages/applications/usecases/ContactMessageUseCases.ts
- backend/chats/messages/domains/entities/contactMessage.ts
- backend/chats/messages/infrastructures/mappers/ContactMessageMapper.ts
- backend/chats/messages/infrastructures/repositories/SbContactMessageRepository.ts
- lib/getUserName.ts
> [Feat] 채팅 페이지 실시간 채팅 구현

- .coderabbit.yaml
- app/(pola)/helps/create/components/ImageUploader.module.css
- app/(pola)/helps/create/components/ImageUploader.tsx
- app/(pola)/helps/create/components/Step3HelpDetails.tsx
- app/(pola)/helps/create/page.tsx
- app/api/images/help/route.ts
- app/api/images/profile/route.ts
- app/layout.tsx
- lib/api_front/help.api.ts
- lib/api_front/images.ts
- lib/contexts/ImageContext.tsx
- lib/hooks/useCreateHelp.ts
- lib/hooks/useImageUpload.ts
- lib/models/createHelpDto.ts
- lib/models/getImageUrl.ts
- 관련 이슈: 
close #103 
---
- Image를 업로드 하는 별도에 컴포넌트 생성
- 해당 컴포넌트와 상위 컴포넌트인 page.tsx에서 사용하는 이미지 데이터를 통일하기 위해 contextAPI 사용
- contextAPI를 통해 전역 이미지 데이터 구현
- page.tsx에서 submit 됐을 경우 이미지를 storage에 업로드 후 return된 URL 배열을 return하는 useImageUpload hook 구현.
---
> [Refactor] 이미지 업로드 컴포넌트 및 API 동작 모듈화

- app/api/scores/user-with-category/route.ts
- app/api/scores/user-with-season/route.ts
- app/api/scores/user/route.ts
- app/api/seniors/help/route.ts
- backend/helps/domains/entities/CommonHelpEntity.ts
- backend/helps/infrastructures/repositories/SbCommonHelpRepository.ts
- backend/juniors/scores/ScoreModel.ts
- backend/juniors/scores/applications/dtos/ScoreRequestDto.ts
- backend/juniors/scores/applications/usecases/ScoreUseCases.ts
- backend/juniors/scores/domains/entities/Score.ts
- backend/juniors/scores/domains/repositories/ScoreRepositoryInterface.ts
- backend/juniors/scores/infrastructures/mappers/ScoreMapper.ts
- backend/juniors/scores/infrastructures/repositories/ScoreRepository.ts
- backend/seniors/helps/applications/dtos/SeniorRequest.ts
- backend/seniors/helps/domains/entities/SeniorHelp.ts
- backend/seniors/helps/infrastructures/mappers/SeniorHelpMapper.ts
- backend/seniors/helps/infrastructures/repositories/SeniorHelpRepositories.ts
- 관련 이슈:
close #110 
close #111
---
-  help 생성 시 category 배열이 help_category 테이블에 저장되지 않는 문제 해결
- 카테고리가 복수로 help_category 테이블에 저장되지 않는 버그 해결
- 
---
> [Refactor] 백엔드 관련 로직 수정(점수 관련, 카테고리 관련)

- app/(pola)/main/_components/junior/JuniorMain.tsx
- app/api/seniors/helps/route.ts
- app/page.tsx
- 관련 이슈:
---
- []
- []
- []
---
> Fix: Fix Build error

- lib/http.api.ts
- middleware.ts
- next.config.ts
- 관련 이슈:
---
- []
- []
- []
---
> [Bug] 베포 시 CORS 에러 수정

- app/(pola)/helps/[helpId]/_components/help-content/HelpContent.tsx
- 관련 이슈:
---
- []
- []
- []
---
> [Feat] 카테고리 ID를 이름으로 변환하는 유틸리티 함수 추가

- app/(pola)/main/_components/junior/JuniorMain.tsx
- app/(pola)/user/profile/[nickname]/page.tsx
- app/_components/commons/list-card/help-list-card/HelpListCard.tsx
- app/_components/sections/user-tier/UserTierSection.tsx
- lib/api_front/score.api.ts
- lib/hooks/useScores.ts
- next.config.ts
- 관련 이슈:
---
- []
- []
- []
---
> [Refactor] 유저 프로필섹션 변경

- app/(pola)/user/profile/[nickname]/_components/user-helps/junior/UserHelpsSection.tsx
- app/(pola)/user/profile/[nickname]/_components/user-helps/junior/userHelps.module.css
- app/(pola)/user/profile/[nickname]/page.tsx
- lib/utils/categoryUtils.ts
- 관련 이슈:
---
- []
- []
- []
---
> [Feat] 사용자 헬프 섹션에 점수 API 추가 및 헬프 카테고리 시각화 개선. CSS 클래스 추가로 각 카테고리 색상 구분.

- app/(pola)/chats/list/_components/ChatListItems.module.css
- app/(pola)/chats/list/_components/ChatListItems.tsx
- app/(pola)/main/_components/junior/sections/content/Calendar.module.css
- app/(pola)/user/profile/[nickname]/_components/user-helps/junior/userHelps.module.css
- 관련 이슈:
---
- []
- []
- []
---
> feat : 채팅리스트, 캘린터, 마이페이지 수정

- app/(pola)/chats/[roomId]/_components/HelpInfo.module.css
- app/(pola)/chats/[roomId]/_components/HelpInfo.tsx
- app/(pola)/chats/[roomId]/history/page.tsx
- app/(pola)/chats/list/_components/ChatListItems.module.css
- app/(pola)/chats/list/_components/ChatListItems.tsx
- app/(pola)/main/_components/senior/SeniorMain.tsx
- app/(pola)/user/profile/[nickname]/_components/user-helps/junior/UserHelpsSection.tsx
- app/(pola)/user/profile/[nickname]/page.tsx
- app/_components/commons/list-card/help-list-card/HelpListCard.module.css
- app/_components/commons/list-card/help-list-card/HelpListCard.tsx
- app/api/juniors/helps/accepted/route.ts
- app/api/reviews/user-stats/route.ts
- backend/juniors/helps/applications/usecases/JuniorAcceptedHelpsUseCase.ts
- backend/juniors/helps/domains/repositories/IJuniorHelpStatusRepository.ts
- backend/juniors/helps/infrastructures/repositories/JuniorHelpStatusInfrastructure.ts
- lib/api_front/junior-help.api.ts
- lib/constants/api.ts
- lib/hooks/index.ts
- lib/hooks/junior/useJuniorAcceptedHelps.ts
close #178 
- 관련 이슈:
---
- junior가 참여한 helps 목록 가져오기 API 및 연결 구현
- HelpListCard 컴포넌트의 category 전체 개수 API 연결 및 2개 이상 넘어가면 +n 개로 표시
- 채팅 관련 페이지에서 프로필 이미지 클릭 시 해당 닉네임에 프로필 페이지로 이동
- review 별점 평균을 내는 로직을 star_point 테이블에서 가져와 평균 내도록 변경
---
> [Feat] 자잘한 내용 수정

- app/(pola)/user/profile/[nickname]/settings/page.module.css
- 관련 이슈:
---
- []
- []
- []
---
> feat : 유저/설정 css 수정

- app/(pola)/helps/create/components/Step3HelpDetails.module.css
- app/(pola)/helps/create/components/Step3HelpDetails.tsx
- 관련 이슈:
---
- []
- []
- []
---
> feat : Step3HelpDetails.tsx 관련 수정

- app/_components/commons/list-card/help-list-card/HelpListCard.tsx
- 관련 이슈:
---
- []
- []
- []
---
> feat: 카테고리별 점수 계산 로직 수정 및 표시 형식 변경

- app/_components/commons/common-sections/user-info/UserInfoSection.tsx
- 관련 이슈:
close #186 
---
- 유저 섹션에 평점 API 연결
---
> [Feat] 사용자 섹션에 별점 API 연결

- app/(pola)/login/_styles/login.module.css
- 관련 이슈:
---
- []
- []
- []
---
> feat : 로그인 css 수정

- app/(pola)/user/profile/[nickname]/page.tsx
- app/_components/commons/list-card/help-list-card/HelpListCard.tsx
- app/_components/sections/user-tier/UserTierSection.tsx
- app/_components/sections/user-tier/userTier.module.css
- lib/constants/categories.ts
- 관련 이슈:
---
- []
- []
- []
---
> [fix] 오류 수정

- app/page.tsx
- next.config.ts
- 관련 이슈:
---
- []
- []
- []
---
> 온보딩 페이지 리팩토링 및 이미지 도메인 설정 개선
